version: "3"
services:
  app:
    build: .
    volumes:
      - '.:/usr/src/app'
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=inno
      - MYSQL_ROOT_PASSWORD=inno
    ports:
      - 3306:3306
